"use strict";

// Public half of the license signing key. The private half lives ONLY in license-private.key
// on the vendor's machine (gitignored). Generated by tools/license.js keygen.
module.exports = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAnK1lbl2vlbPIExhQhJxnIiLxamxCiRMCdYeob2660h4=\n-----END PUBLIC KEY-----\n";
