#!/usr/bin/env node
"use strict";

/**
 * License key tooling (vendor side). Keys are Ed25519-signed, verified offline by the app.
 *
 *   node tools/license.js keygen                      one-off: creates license-private.key (SECRET, gitignored)
 *                                                     and writes the public key into src/main/licensePublicKey.js
 *   node tools/license.js issue --name "Ada Lovelace" --email ada@example.com [--days 365] [--note "Invoice 42"]
 *   node tools/license.js verify <key>
 *
 * Key format:  EV1.<base64url payload>.<base64url signature>
 * Payload:     { id, name, email, issued, expires|null, note }
 */

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const ROOT = path.join(__dirname, "..");
const PRIVATE_KEY_FILE = path.join(ROOT, "license-private.key");
const PUBLIC_KEY_MODULE = path.join(ROOT, "src", "main", "licensePublicKey.js");

const b64u = (buf) => Buffer.from(buf).toString("base64url");

function keygen() {
  if (fs.existsSync(PRIVATE_KEY_FILE)) {
    console.error(`Refusing to overwrite ${PRIVATE_KEY_FILE}. Delete it first if you really want a new key pair (existing licenses would stop validating).`);
    process.exit(1);
  }
  const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
  fs.writeFileSync(PRIVATE_KEY_FILE, privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
  const pub = publicKey.export({ type: "spki", format: "pem" });
  fs.writeFileSync(PUBLIC_KEY_MODULE, `"use strict";\n\n// Public half of the license signing key. The private half lives ONLY in license-private.key\n// on the vendor's machine (gitignored). Generated by tools/license.js keygen.\nmodule.exports = ${JSON.stringify(pub)};\n`);
  console.log(`Private key: ${PRIVATE_KEY_FILE}  (keep it secret, back it up)`);
  console.log(`Public key written to ${path.relative(ROOT, PUBLIC_KEY_MODULE)}`);
}

function arg(args, name, fallback) {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : fallback;
}

function issue(args) {
  if (!fs.existsSync(PRIVATE_KEY_FILE)) { console.error("No license-private.key — run: node tools/license.js keygen"); process.exit(1); }
  const name = arg(args, "--name"); const email = arg(args, "--email");
  if (!name) { console.error("--name is required"); process.exit(2); }
  const days = arg(args, "--days"); const note = arg(args, "--note", "");
  const issued = new Date();
  const expires = days ? new Date(issued.getTime() + parseInt(days, 10) * 86400000) : null;
  const payload = { id: crypto.randomBytes(6).toString("hex"), name, email: email || "", issued: issued.toISOString().slice(0, 10), expires: expires ? expires.toISOString().slice(0, 10) : null, note };
  const data = Buffer.from(JSON.stringify(payload));
  const privateKey = crypto.createPrivateKey(fs.readFileSync(PRIVATE_KEY_FILE));
  const sig = crypto.sign(null, data, privateKey);
  const key = `EV1.${b64u(data)}.${b64u(sig)}`;
  console.log(key);
  console.error(`\nIssued to ${name}${email ? ` <${email}>` : ""}, ${expires ? "expires " + payload.expires : "no expiry"}, id ${payload.id}`);
}

function verify(args) {
  const { verifyLicenseKey } = require(path.join(ROOT, "src", "main", "license.js"));
  const r = verifyLicenseKey(args[0] || "");
  console.log(JSON.stringify(r, null, 2));
  process.exit(r.valid ? 0 : 1);
}

const [cmd, ...rest] = process.argv.slice(2);
if (cmd === "keygen") keygen();
else if (cmd === "issue") issue(rest);
else if (cmd === "verify") verify(rest);
else { console.log("usage: license.js keygen | issue --name N [--email E] [--days D] [--note T] | verify <key>"); process.exit(2); }
